### ISSUE TITLE
Build failled

### ISSUE THREAD

**Issue by balkrishanyadav** [alexakasanjeev/magento_react_native#102]
**Describe the bug**
I am unable to run app using terminal in ios.

**Expected behavior**
Getting error build faile 

"Undefined symbols for architecture x86_64:
  "associated type descriptor for FloatLiteralType", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "associated type descriptor for IntegerLiteralType", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "value witness table for Builtin.Int32", referenced from:
      full type metadata for __C.YGUnit in libYogaKit.a(YGLayoutExtensions.o)
  "protocol witness table for Swift.Float : Swift._ExpressibleByBuiltinFloatLiteral in Swift", referenced from:
      associated type witness table accessor for FloatLiteralType : Swift._ExpressibleByBuiltinFloatLiteral in __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "protocol witness table for Swift.Int : Swift._ExpressibleByBuiltinIntegerLiteral in Swift", referenced from:
      associated type witness table accessor for IntegerLiteralType : Swift._ExpressibleByBuiltinIntegerLiteral in __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "protocol descriptor for Swift.ExpressibleByFloatLiteral", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "method descriptor for Swift.ExpressibleByFloatLiteral.init(floatLiteral: A.FloatLiteralType) -> A", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "associated conformance descriptor for Swift.ExpressibleByFloatLiteral.FloatLiteralType: Swift._ExpressibleByBuiltinFloatLiteral", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByFloatLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "protocol descriptor for Swift.ExpressibleByIntegerLiteral", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "method descriptor for Swift.ExpressibleByIntegerLiteral.init(integerLiteral: A.IntegerLiteralType) -> A", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "associated conformance descriptor for Swift.ExpressibleByIntegerLiteral.IntegerLiteralType: Swift._ExpressibleByBuiltinIntegerLiteral", referenced from:
      protocol conformance descriptor for __C.YGValue : Swift.ExpressibleByIntegerLiteral in YogaKit in libYogaKit.a(YGLayoutExtensions.o)
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_YogaKit)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_YogaKit)
  "_swift_getForeignTypeMetadata", referenced from:
      type metadata accessor for __C.YGValue in libYogaKit.a(YGLayoutExtensions.o)
      type metadata accessor for __C.YGUnit in libYogaKit.a(YGLayoutExtensions.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'CocoaAsyncSocket' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'OpenSSL-Universal' from project 'Pods')
warning: no rule to process file '/Users/balkrishanyadav/Desktop/magento_react_native/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/balkrishanyadav/Desktop/magento_react_native/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/balkrishanyadav/Desktop/magento_react_native/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
build session not created after 15 seconds - still waiting
build session not created after 30 seconds - still waiting
build session not created after 45 seconds - will continue waiting until success

** BUILD FAILED **

The following build commands failed:
	Ld /Users/balkrishanyadav/Library/Developer/Xcode/DerivedData/magento_react_native-byezfiknxwombkdsxfpnwswsxopz/Build/Products/Debug-iphonesimulator/magento_react_native.app/magento_react_native normal x86_64
(1 failure)"

**Smartphone (please complete the following information):**
 - Magento Version: [e.g. 2.1.0]
 - Device: [e.g. iPhone6] -> iPhone11 simulator
 - OS: [e.g. iOS8.1] iOS 13

**Comment by alexakasanjeev** [comment]
hi @balkrishanyadav  let me check, meanwhile did you installed pod files by running `pod install` by going inside `ios` folder

**Comment by balkrishanyadav** [comment]
Thanks Sanjeev ...
yes i followed same process as mentioned in documentation link...

**Comment by alexakasanjeev** [comment]
@balkrishanyadav Please try now, by pulling new commits

**Comment by balkrishanyadav** [comment]
@alexakasanjeev Still getting error for FlipperClient not found undeclared.

I run application from terminal and through direct xCode in both case getting same error...

/magento_react_native/ios/magento_react_native/AppDelegate.m:21:3: error: use of undeclared identifier 'FlipperClient'
  FlipperClient *client = [FlipperClient sharedClient];
  ^
/magento_react_native/ios/magento_react_native/AppDelegate.m:21:18: error: use of undeclared identifier 'client'
  FlipperClient *client = [FlipperClient sharedClient];

**Comment by troublediehard** [comment]
@balkrishanyadav I've just checked with a fresh clone of the repository and can confirm the issue is resolved. 

It's likely cache or updates with new changes issue. To make sure it's working just do fresh clone of repository.

**Comment by alexakasanjeev** [comment]
@all-contributors please add @balkrishanyadav for bug
