### ISSUE TITLE
I facing issue when build the app. cant get product.sku.

### ISSUE THREAD

**Issue by Pohhong97** [alexakasanjeev/magento_react_native#112]
I follow the documentation to setup .  but facing issue on this please advise 
![Screenshot 2020-09-29 at 2 24 55 PM](https://user-images.githubusercontent.com/50574725/94520878-a5199d00-025f-11eb-853d-f5251ca990d2.png)

I follow the documentation to set up Magento site and app. And double confirm on it. But it showing out this error. Please advise me .

**Comment by alexakasanjeev** [comment]
Hi @Pohhong97 I yesterday updated some redundant code, try taking a pull from `develop` branch and try again, let me know if error occurs :)

**Comment by Pohhong97** [comment]
> Hi @Pohhong97 I yesterday updated some redundant code, try taking a pull from `develop` branch and try again, let me know if error occurs :)

That was great. Everything works fine right now. Thank you so much.

**Comment by alexakasanjeev** [comment]
closing the issue, now, feel free to contribute back if you find some issues or if you can add feature :)
