### ISSUE TITLE
Facing issue on APP didnt show image.

### ISSUE THREAD

**Issue by Pohhong97** [alexakasanjeev/magento_react_native#113]
I was upload to Magento web.
And the app has shown the product category but didn't load out the image. I had tried to refresh the cache. Please advise me 
thank you

**Comment by alexakasanjeev** [comment]
Hi, is your magento setup on local-host or you have hosted somewhere on external server?

Because if, your magento website is on localhost, the url for image is http, not https, and Android doesn't load image over http.
If your magento website is on your localhost, you can modify 

[src/magento/index.js](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/magento/index.js) file like this, to load images while in development only

```
getMediaUrl() {
    return `${this.storeConfig.base_media_url}`.replace(
      'localhost',
      '10.0.2.2',
    );
  }

  getProductMediaUrl() {
    return `${this.storeConfig.base_media_url}catalog/product`.replace(
      'localhost',
      '10.0.2.2',
    );
  }
```

**Comment by Pohhong97** [comment]
> Hi, is your magento setup on local-host or you have hosted somewhere on external server?
> 
> Because if, your magento website is on localhost, the url for image is http, not https, and Android doesn't load image over http.
> If your magento website is on your localhost, you can modify
> 
> [src/magento/index.js](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/magento/index.js) file like this, to load images while in development only
> 
> ```
> getMediaUrl() {
>     return `${this.storeConfig.base_media_url}`.replace(
>       'localhost',
>       '10.0.2.2',
>     );
>   }
> 
>   getProductMediaUrl() {
>     return `${this.storeConfig.base_media_url}catalog/product`.replace(
>       'localhost',
>       '10.0.2.2',
>     );
>   }
> ```

Yes, I host magento local. I cant able find the index.js . Are the command just put inside it then done ?

**Comment by Pohhong97** [comment]
Great solution . I can able to view the image right now . Thank you so much .

**Comment by Pohhong97** [comment]
When i click into the product, it shows like the image. Please advise me 
![Screenshot 2020-10-05 at 9 23 16 AM](https://user-images.githubusercontent.com/50574725/95032295-92ceb180-06ec-11eb-83e7-8ff2352f2c8c.png)

**Comment by alexakasanjeev** [comment]
@Pohhong97 the magento store that you are testing on is it hosted on remote or on your localhost?

**Comment by Pohhong97** [comment]
Localhost

**Comment by alexakasanjeev** [comment]
Will look into the problem, will update here

**Comment by alexakasanjeev** [comment]
This issue is fixed

**Comment by Pohhong97** [comment]
Ok. Thank you. Waiting for your update

**Comment by alexakasanjeev** [comment]
Which update you are talking about?

the particular error is fixed, and merged in develop branch

**Comment by Pohhong97** [comment]
I mean error when clicking into the product page.

**Comment by Pohhong97** [comment]
> Which update you are talking about?
> 
> the particular error is fixed, and merged in develop branch

Just saw your new merged . I tested it fixed. Thank you so much
