### ISSUE TITLE
Unexpected token, expected ","  CatalogGridItem

### ISSUE THREAD

**Issue by arjunadobe** [alexakasanjeev/magento_react_native#114]
Hi, I am getting this error 

error: SyntaxError: D:\native\one\src\common\CatalogGridItem\CatalogGridItem.js: Unexpected token, expected "," (74:18)

  72 |   const navigation = useNavigation();
  73 |   const extra = useSelector(state =>
> 74 |     [product.sku] in state[stateAccessor].extra
     |                   ^

I have 1 categories with 5 products and added that categories as a feature categories. All the products are simple. Anyone have a idea why I am getting error. 

I am getting this error in Magento 2.4

**Comment by alexakasanjeev** [comment]
hi @arjunadobe I recently updated a lot of code, could you take a new pull from `develop` branch and run again, and report back if issue stills occurs

**Comment by arjunadobe** [comment]
Hi,

Now I took the latest pull and I cam getting this error
![Screenshot_2020-10-05-11-46-43-60_9892beabec95f49831662c525eeb3b10](https://user-images.githubusercontent.com/51747982/95046016-e1864680-0700-11eb-8b4b-cea1a7c5cb20.jpg)
![Screenshot_2020-10-05-11-46-57-45_9892beabec95f49831662c525eeb3b10](https://user-images.githubusercontent.com/51747982/95046021-e3500a00-0700-11eb-9b09-84f92659ceaf.jpg)
![Screenshot_2020-10-05-11-45-43-57_9892beabec95f49831662c525eeb3b10](https://user-images.githubusercontent.com/51747982/95046024-e519cd80-0700-11eb-85f5-ec34e811afb3.jpg)
![Screenshot_2020-10-05-11-46-22-50_9892beabec95f49831662c525eeb3b10](https://user-images.githubusercontent.com/51747982/95046029-e6e39100-0700-11eb-9a28-a462c0c2bc40.jpg)

**Comment by alexakasanjeev** [comment]
@arjunadobe you can ignore warnings, they are not critical, plus on release build they don't show up

Regarding last screenshot, did you get this error as soon as you run the project, or after you have made some modification in code and then see this error

**Comment by arjunadobe** [comment]
Regarding the last error: I didn't do any modification still now. I am getting this error, when I am visiting any categories, products. Actually I am unable to proceed anything except homepage.

Also is there any way to disable this warnings in development module.

**Comment by alexakasanjeev** [comment]
You can comment out thsi line in [App.js](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/App.js) to hide warnings box

```
// require('react-native').unstable_enableLogBox();
```


Regarding error, that is a serious matter, is your magento store on localhost or on server, if it's on server, you can share details with me so that i can look at my end

**Comment by arjunadobe** [comment]
I have sent an email with all the credentials

**Comment by alexakasanjeev** [comment]
Thank you @arjunadobe for sharing it, allow me minimum 3 days, as I am full time office work, I will look into the problem, at spare time, will try to fix soon

**Comment by alexakasanjeev** [comment]
This issue is fixed
