### ISSUE TITLE
JSON Parse error: Unexpected Identifier "New"

### ISSUE THREAD

**Issue by siprabin** [alexakasanjeev/magento_react_native#23]
When I try to run using react-native run-android opening the application in my mobile. but showing the error in Home Page.

> JSON Parse error: Unexpected Identifier "New"

Can anyone help?

**Comment by alexakasanjeev** [comment]
Hi @siprabin, can you give more context on how to reproduce the bug, because I try running the app and it is working fine,

did you provide your own magento store url in `magento.js` file?
Please elaborate the steps you did from cloning to running the app

**Comment by siprabin** [comment]
Working fine now. Thanks @alexakasanjeev

**Comment by alexakasanjeev** [comment]
Happy to help @siprabin, if you want to contribute back to the project, it's really easy I have written detail [guide](https://github.com/alexakasanjeev/magento_react_native/blob/develop/CONTRIBUTING.md) on how to do that.

And little late, but thanks to you I wrote the new setup guide with images ,
https://github.com/alexakasanjeev/magento_react_native/wiki/Setup
