### ISSUE TITLE
Upgrade: React Native from 0.59.5 to 0.61.2

### ISSUE THREAD

**Issue by alexakasanjeev** [alexakasanjeev/magento_react_native#35]
**Is your feature request related to a problem? Please describe.**
React native >= 0.60 has some major changes like
- AndroidX support
- Hermes(new JavaScript engine) support
- 64 bit support
- fast refresh
- Auto link library (no need to manually link packages)
- With Hermes unable, build size decreases and performance improves

**Describe the solution you'd like**
Follow these steps to upgrade react native
1. Run the `upgrade` command

    ```
    react-native upgrade
    ```

    > Some files will not get upgraded, those files need to be changes manually
2. Open [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/) and choose 0.59.2 in left column and latest react native version in right column
![react-native-upgrade](https://user-images.githubusercontent.com/13250741/66507532-f8458d80-eaec-11e9-9395-9fe51fea6357.png)
3. Files which were not changes automatically in Step 1, modified them manually using step 2
4. Unlink previously linked modules
5. Run and test App

**Additional context**
Official React Native upgrade [guide](https://facebook.github.io/react-native/docs/0.60/upgrading)
To upgrade `ios/magento_react_native.xcodeproj/project.pbxproj` file follow this [guide](https://github.com/react-native-community/upgrade-helper/issues/47)

**TODO**
- [x] Upgrade react native from `0.59.5` to `^0.61.2` 
- [ ] Enable hermes 
- [x] Test entire app for any case of failure

**Comment by alexakasanjeev** [comment]
Working on it

**Comment by DevDelvo** [comment]
I'd like to work on this!
