### ISSUE TITLE
Build the project on iOS and test

### ISSUE THREAD

**Issue by alexakasanjeev** [alexakasanjeev/magento_react_native#40]
**Are there certain things to report that are not a bug or feature?**
The app hasn't been tested on iOS device, need to build and properly test on iOS device.

- [ ] Test on iOS device with and without notch
- [ ] To upgrade `ios/magento_react_native.xcodeproj/project.pbxproj` file follow this [guide](https://github.com/react-native-community/upgrade-helper/issues/47)
- [ ] Fix any linking problem if occurs
- [ ] Take screenshots for iOS

**Comment by josectobar** [comment]
I'd like to take this.

**Comment by alexakasanjeev** [comment]
Yes please, it would be great help, please let me know if you are stuck any step. :smile: 

also I updated recently React Native to 0.61.2, so I haven't configured this step
To upgrade `ios/magento_react_native.xcodeproj/project.pbxproj` file follow this [guide](https://github.com/react-native-community/upgrade-helper/issues/47)

**Comment by josectobar** [comment]
It looks like there are errors related to the material icons, do you want me to create a ticket for this?
