### ISSUE TITLE
App is too slow

### ISSUE THREAD

**Issue by harshitmahendra** [alexakasanjeev/magento_react_native#47]
After making the release Build when I opened the app the response and animation of the app is too slow .. 

When I tried the app after removing the sample data from my Magento, then also app is too slow..

Any idea about that ??

**Comment by alexakasanjeev** [comment]
Hi @harshitmahendra, I faced this issue only when I tried upgrading `react-native` to 0.60.5 and in debug mode (but that code hasn't been merged to `develop` branch)

Can you please answer these questions?
1. Which branch are you on `develop` or `feature/react-native-upgrade`?
2. On which device the app is tested, (if tested on Emulator, can you test on Physical device)?
3. Are you using your own magento store url or the one already present in the code?

**Comment by harshitmahendra** [comment]
answers
1. I am using the develop branch
2. I am using the Physical device to test
3. I am my own Magento store url [http://fiji.jaipurshine.com](http://fiji.jaipurshine.com) 

I think is the problem in the drawer, the categories is loaded every page

**Comment by alexakasanjeev** [comment]
> ok, can you share the `base url` and `access_token`(you  can delete afterwards that token or create new one) here or on my mail `sanjeevy133@protonmail.com`,

Meanwhile, try removing `DrawerNavigation` from navigation, replace the code in [src/navigation/index.js](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/navigation/index.js) with this
```[javascript]
import { createAppContainer } from 'react-navigation';
import MainAppNavigator from './MainAppNavigator';

const Navigator = createAppContainer(MainAppNavigator);

export default Navigator;
```

**Comment by alexakasanjeev** [comment]
@troublediehard could you please create a debug build from `develop` branch using your magento url and check whether the App is running slow(whenever you have time)
