### ISSUE TITLE
App Crash At The Time Of Checkout When Selecting One Country at the Magento2 Backend

### ISSUE THREAD

**Issue by harshitmahendra** [alexakasanjeev/magento_react_native#52]
The app crash at the time of checkout, when I selected only **one country** in the Magento 2 backend

I Selected Country Fiji at the Magento 2 backend and at the time of checkout it gives an Error like :
**getCountryData() is not an Object.(evaluating 'available_reagion' in getCountryData())**

Here is the screen shot :
![Screenshot_1569413919](https://user-images.githubusercontent.com/34433141/65600799-76b71100-dfbe-11e9-8ecf-e74b8275942f.png)

I Tested both on Emulator and Real Device, It gives and the same error

**Comment by alexakasanjeev** [comment]
Hi @harshitmahendra I have fixed the issue, could you check the app using branch [`hotfix/country-selection`](https://github.com/alexakasanjeev/magento_react_native/tree/hotfix/country-selection)

The code will be merged to `develop` branch, after bit testing

**Comment by alexakasanjeev** [comment]
@all-contributors please add harshitmahendra for bug
