### ISSUE TITLE
Fix missing font family for ios in typography

### ISSUE THREAD

**Issue by alexakasanjeev** [alexakasanjeev/magento_react_native#56]
**Describe the bug**
`sans-serif` font family is not available in iOS, so app will crash.

**Current Behavior**
App will crash in iOS device

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. Open [typography.js](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/typography.js)
2. Change these lines
    ```javascript
    import colors from './colors';

    const fontFamily = 'sans-serif';
    ```
3. With these lines
     ```javascript
    import { Platform } from 'react-native';
    import colors from './colors';

    const fontFamily = Platform.select({ android: 'sans-serif', ios: 'Helvetica' });
    ```

**Additional context**

**Comment by ishansinghania** [comment]
Can i do this?

**Comment by alexakasanjeev** [comment]
No :laughing:

**Comment by ishansinghania** [comment]
definitely!
