### ISSUE TITLE
[iOS] Configurable option UI not rendring properly .

### ISSUE THREAD

**Issue by MehmoodArib** [alexakasanjeev/magento_react_native#67]
**Configurable option UI not rendering properly**
Drop down menu where we choose size and color of the `configurable` product and on address page where we select country & region are not rendering properly in iOS.

**Expected behavior**
Drop down should remain hidden, and should only open when clicked.

**Current Behavior**
Drop-down is open by default in iOS, which makes it hard to use, and if two of those are present side by side, their UI is overlapping with each other, making it hard to select.

**Steps to Reproduce**
1. Open the app.
2. Select any `configurable` item like(t-shirt).

**Screenshots**
> Product Detail Screen
![product](https://user-images.githubusercontent.com/13250741/67315337-fe436180-f523-11e9-9a97-1c9075c2b1d2.png)

> Address Screen at the time of checkout
![Simulator Screen Shot - iPhone 11 - 2019-10-22 at 13 42 49](https://user-images.githubusercontent.com/32247358/67268654-a4ff1200-f4d2-11e9-814e-21a97c94f1dc.png)

**Smartphone (please complete the following information):**
 - Magento Version: [2.1.0]
 - Device: [iPhone11]
 - OS: [iOS 13.0]

**Comment by alexakasanjeev** [comment]
**Solution**
1. install `react-native-modal-selector` follow [doc](https://github.com/peacechen/react-native-modal-selector)
2. Create a new component `ModalSelect` that will be a wrapper around `react-native-modal-selecotor` in `components/molecule` folder
> See https://github.com/troublediehard/magento-react-native/blob/master/src/components/common/ModalSelect.js
3. Write stories for `ModalSelect` using `storybook`
3. Use this custom `ModalSelect` component and use it everywehere

**Comment by alexakasanjeev** [comment]
@all-contributors please add MehmoodArib for bug
