### ISSUE TITLE
Getting Currency Symbol Error 

### ISSUE THREAD

**Issue by piyush9015** [alexakasanjeev/magento_react_native#82]
Hi,
My website belongs to kuwait . And i am using Kuwati Dinnar in currency . Now as i can for USD its working fine . But when i changed currency KWD. It is giving error . When i tried to installed it . That time it was also showing currency symbol warning .

**Comment by alexakasanjeev** [comment]
Hi @piyush9015 Thank you so much for pointing out the problem, I'm aware of the currency problem, currently the currency isn't implemented correctly, #58 will soon work on this issue. Meanwhile please answer following questions. :smile: 

1. Are you setting the default currency to `kuwait` in the magento backend?
2. Are you giving support to multiple currency or single currency?
2. Could you send me some screenshots here of the app after changing your currency.

> I would request you to test the app and report more issues, would help to make this app better :smile:

**Comment by piyush9015** [comment]
Thank you so much for your reply . I really appreciate it . I want to let you know that . I did not change currency . It is my default currency . If i changed it USD . Than app start displaying currency $. But for my base currency it is showing null.  Please find the attachment .
________________________________

**Comment by piyush9015** [comment]
![Screenshot_60](https://user-images.githubusercontent.com/24675931/68670428-f80e3700-055d-11ea-8012-742061aa97c0.png)
My base currency is kwd . and i also updated magento.js file 


**
 * Magento Settings for the app,
 * Follow instructions: https://github.com/alexakasanjeev/magento_react_native/wiki/Setup
 *
 * url                     : Base url of the magento website
 * home_cms_block_id       : Block id which conatin json data,
 *                           which will be shown in Home screen
 * password_reset_template : Email template name in magento backend,
 *                           use for sending password reset e-mail
 * access_token            : Token to access magento API, without it
 *                           app won't work
 */
export const magentoOptions = {
  url: 'http://95.168.186.193/~cahelpsc/',
  home_cms_block_id: 19, // required int
  password_reset_template: 'email_reset',
  authentication: {
    integration: {
      access_token: 'tjz8pfhjzmsfudyg9na5emtbrds9svim',
    }
  }
};

/**
 * Magento 2 REST API doesn't return currency symbol,
 * so manually specify all currency symbol(that your store support)
 * along side their currency code.
 */
export const currencySymbols = Object.freeze({
  USD: '$',
  EUR: '€',
  AUD: 'A$',
  GBP: '£',
  CAD: 'CA$',
  CNY: 'CN¥',
  JPY: '¥',
  SEK: 'SEK',
  CHF: 'CHF',
  INR: '₹',
  KWD: 'د.ك',
});

But i am still getting error . It is showing null

**Comment by piyush9015** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/24675931/68671027-715a5980-055f-11ea-82f1-e9ee4f9a9fcf.png)


My magento currency check the screen shot . Both base and default currency is same kwd

**Comment by alexakasanjeev** [comment]
> ![Screenshot_60](https://user-images.githubusercontent.com/24675931/68670428-f80e3700-055d-11ea-8012-742061aa97c0.png)
> My base currency is kwd . and i also updated magento.js file
> 
> **
> 
>     * Magento Settings for the app,
> 
>     * Follow instructions: https://github.com/alexakasanjeev/magento_react_native/wiki/Setup
> 
>     * url                     : Base url of the magento website
> 
>     * home_cms_block_id       : Block id which conatin json data,
> 
>     * ```
>                             which will be shown in Home screen
>       ```
> 
>     * password_reset_template : Email template name in magento backend,
> 
>     * ```
>                             use for sending password reset e-mail
>       ```
> 
>     * access_token            : Token to access magento API, without it
> 
>     * ```
>                             app won't work
>       ```
> 
> 
> */
> export const magentoOptions = {
> url: 'http://95.168.186.193/~cahelpsc/',
> home_cms_block_id: 19, // required int
> password_reset_template: 'email_reset',
> authentication: {
> integration: {
> access_token: 'tjz8pfhjzmsfudyg9na5emtbrds9svim',
> }
> }
> };
> 
> /**
> 
>     * Magento 2 REST API doesn't return currency symbol,
> 
>     * so manually specify all currency symbol(that your store support)
> 
>     * along side their currency code.
>       */
>       export const currencySymbols = Object.freeze({
>       USD: '$',
>       EUR: '€',
>       AUD: 'A$',
>       GBP: '£',
>       CAD: 'CA$',
>       CNY: 'CN¥',
>       JPY: '¥',
>       SEK: 'SEK',
>       CHF: 'CHF',
>       INR: '₹',
>       KWD: 'د.ك',
>       });
> 
> 
> But i am still getting error . It is showing null

Thank you for reporting, will test build using your url and access_token and will let you know

**Comment by alexakasanjeev** [comment]
Hello @piyush9015, the problem is from your side, you haven't set currency symbol to your chosen currency. In Magento admin panel there is a setting to assign currency symbol to the currency code, since it isn't set, in the API response currency symbol is coming null, and that's what appearing on screen, look `base_currency_symbol` & `default_display_currency)symbol` both are coming null

![currency_symbol_error](https://user-images.githubusercontent.com/13250741/68676248-9c54a580-057f-11ea-9b66-d789ee9a7736.png)
 

Although, I have added a check that will use fallback currency if currency symbol comes null or undefined from backend, this is how it is looking, meanwhile please assign a currency symbol from backend and test again

>Screenshots after adding fallback currency, url is yours
![Screenshot_1573565013](https://user-images.githubusercontent.com/13250741/68676391-f2294d80-057f-11ea-805f-ca883d26e21d.png)

**Comment by alexakasanjeev** [comment]
@all-contributors please add piyush9015 for bug

**Comment by alexakasanjeev** [comment]
Also @piyush9015 I was unable to add any item to cart using your url credentials, most probably the stock quantity of all product is zero, do test the entire app using your magento website, and report any error that you encounter, it would be really helpful to find out existing hidden problem in app

**Comment by piyush9015** [comment]
i need your phone number please . I am also from delhi shahdara living in kuwait and america
________________________________

**Comment by alexakasanjeev** [comment]
@piyush9015 currently I'm out of country, please forward your queries on mail sanjeevy133@protonmail.com
